name: tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows:
      - "contributor check"
    types:
      - completed

env:
  CI: true
  HEAD_SHA: |
    ${{
      github.event.workflow_run.head_sha ||
      github.event.pull_request.head.sha ||
      github.sha
    }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    strategy:
      matrix:
        python_version: ['3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ env.HEAD_SHA }}
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/multi-trigger-setup
        with:
          status-context: '${{ github.job }} (${{ matrix.python_version }})'

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install core dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install packages/fakepkg -r tests/requirements.txt

      - name: Core tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pytest tests -vv

      - name: Cleanup
        if: always()
        uses: ./.github/actions/multi-trigger-cleanup
        with:
          status-context: '${{ github.job }} (${{ matrix.python_version }})'
